plugins {
    id 'java'
    id 'application'
}

subprojects {
    apply plugin: 'java'

    java {
        modularity.inferModulePath = true
    }

    repositories {
        mavenCentral()
    }

    dependencies {
        testImplementation platform('org.junit:junit-bom:5.10.0')
        testImplementation 'org.junit.jupiter:junit-jupiter'
    }

    test {
        useJUnitPlatform()
    }
}

project(':main') {
    apply plugin: 'application'

    dependencies {
        implementation project(':model')
        implementation project(':service')
    }

    application {
        mainModule = 'library.main'
        mainClass = 'com.library.Main'
    }
}

project(':model') {
    //no config
}

project(':service') {
    dependencies {
        implementation project(':model')
    }
}

application {
    mainClass= 'com.library.Main'
}
